

logging.file: logs/application.log
logging:
  level:
      org:
        springframework:
          web: DEBUG
        hibernate: ERROR

server:
  port: 9999

spring:
  h2:
    console:
      enabled: true